development:
  environment: development
  payload:
    param: 'dev valluuee'
    ref: ${{ ref }}
    sha: ${{ sha }}
    short_sha: ${{ short_sha }}
    pr: ${{ pr }}
    target: ${{ target }}
    owner: ${{ owner }}
    repo: ${{ repo }}
    pull_request: ${{ pull_request }}
    commit: ${{ commit }}

staging:
  environment: staging
  required_contexts: ['deploy-readiness-check']
  payload:
    param: 'stag valluuee'

production:
  environment: production
  production_environment: true
  required_contexts: ['deploy-readiness-check', 'deliverybot/promotion']
  payload:
    param: 'prod valluuee'