development:
  environment: development
  params:
    param: 'dev valluuee'

staging:
  environment: staging
  params:
    param: 'stag valluuee'

production:
  environment: production
  production_environment: true
  params:
    param: 'prod valluuee'