name: Release a new sephora_payments gem version

on: workflow_dispatch

jobs:
  test:
    name: Say hello
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Say
      run: echo Hii
