name: Deploy gem

on: workflow_dispatch

jobs:
  run_deploy:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'deployment pending'
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - name: Deploying
      run: echo Deploy completed

    - name: 'deployment success'
      if: success()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'success'
        token: '${{ github.token }}'

    - name: 'deployment failure'
      if: failure()
      uses: 'deliverybot/deployment-status@master'
      with:
        state: 'failure'
        token: '${{ github.token }}'