name: Deploy gem

on:
  push:
    branches:
      - main

jobs:
  run_deploy:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'deployment pending'
      run: echo Hi