name: Release a new sephora_payments gem version

on: workflow_dispatch

jobs:
  release:
    name: Release a new sephora_payments gem version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Say
      run: echo Hii
