name: Tests

on: push

jobs:
  rspecs:
    name: Rspecs tests
    runs-on: ubuntu-latest
    steps:
    - name: Run setup
      run: echo 'Some setup finished'
    - name: Run rspecs
      run: echo 'Rspecs finished successfully'

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run setup and test
      run: |
        echo 'Some setup finished'
        echo 'Tested successfully'

  failed:
    runs-on: ubuntu-latesttttt

  deploy:
    runs-on: ubuntu-latest
    needs: [rspecs, tests]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Deploy app to production
      run: |
        echo 'Precompile finished'
        echo 'Deployed successfully'

  failed-deploy:
    runs-on: ubuntu-latest
    needs: [rspecs, tests, failed]
    steps:
    - name: Deploy app to production
      run: |
        echo 'Precompile finished'
        echo 'Deployed successfully'